version: '2'

services:
  db: 
    image: 'postgres:10'
    volumes: 
      - ./pgdata:/var/lib/postgres/data
    environment:    
      POSTGRES_PASSWORD: test

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:test@db/todo"
